versions:
  kubePrometheusStack: 82.1.0 # "61.9.0"
  prometheusAdapter: 5.2.1 #"4.10.0"
  blackboxExporter: 11.8.0  #"9.0.0"
  loki: 6.53.0  # "6.12.0"
  promtail: 6.17.1 #"6.16.0"
  tempo: 1.24.4 # "1.10.3"

features:
  prometheusAdapter: true
  blackboxExporter: true
  loki: true
  promtail: true
  tempo: true

cluster:
  #storageClassName: "gp3"         # e.g. EKS: gp3, GKE: standard-rwo, AKS: managed-csi
  ingressClassName: "apisix"       # e.g. nginx / traefik / alb
  #issuerName: "letsencrypt-prod"  # cert-manager ClusterIssuer

dns:
  grafanaHost: "grafana.danielkaeser2026.de"
  alertmanagerHost: "alertmanager.danielkaeser2026.de"
  prometheusHost: "prometheus.danielkaeser2026.de"
