# Production overrides (edit me)
features:
  loki: true
  promtail: true
  tempo: true
  blackboxExporter: true
  prometheusAdapter: false

cluster:
  #storageClassName: "gp3"         # e.g. EKS: gp3, GKE: standard-rwo, AKS: managed-csi
  ingressClassName: "apisix"       # e.g. nginx / traefik / alb
  #issuerName: "letsencrypt-prod"  # cert-manager ClusterIssuer

dns:
  grafanaHost: "grafana.danielkaeser2026.de"
  alertmanagerHost: "alertmanager.danielkaeser2026.de"
  prometheusHost: "prometheus.danielkaeser2026.de"
